services:
  app:
    build: .
    restart: always
    container_name: playit-tasks-backend
    ports:
      - "8001:8001"
    networks:
      - skynet
    volumes:
      - uploads:/uploads
    depends_on:
      - redis
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: ${REDIS_HOST:-playit-tasks-redis}
    restart: always
    ports:
      - "6379:6379"
    networks:
      - skynet
    # При необходимости можно постоянно хранить данные Redis с помощью Volumes
#    volumes:
#      - redis-data:/data

networks:
  skynet:
    external: true

volumes:
  uploads:
#  redis-data: